### ISSUE TITLE
[COSMIC REEF] Project #250

### ISSUE THREAD

**Issue by sarahrossien** [ArtBlocks/artbot#192] opened 2022-01-29 17:37 UTC
- Project Title: Cosmic Reef
- Project Size: 1024
- Project ID: 250
- Artist Channel ID: 933419567722664016

**Comment by jakerockland** [comment] 2022-01-31 16:41
@ab-hxm @Jbern16 sending this your way for further triage.

**Comment by ab-hxm** [comment] 2022-01-31 19:30
👀

**Comment by ab-hxm** [comment] 2022-01-31 19:47
duplicate of: https://github.com/ArtBlocks/artbot/pull/195

**Closed** 2022-01-31 19:51 UTC
Labels: curated, project-query-support
